import type { Metadata } from "next";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { FadeUp } from "@/components/FadeUp";
import { SmallCaps } from "@/components/SmallCaps";

export const metadata: Metadata = {
  title: "Privacy — Aora",
  description:
    "How Aora, Inc. handles data from AORA Nano and the Chrome extension. On-device first. No data sold.",
  openGraph: {
    title: "Privacy — Aora",
    description:
      "How Aora, Inc. handles data from AORA Nano and the Chrome extension. On-device first. No data sold.",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy — Aora",
    description:
      "How Aora, Inc. handles data from AORA Nano and the Chrome extension. On-device first. No data sold.",
  },
};

type Section = {
  index: string;
  title: string;
  body: React.ReactNode;
};

const EMAIL_LINK = (
  <a
    href="mailto:dev@aoramind.com"
    style={{
      color: "var(--paper)",
      borderBottom: "1px solid var(--green)",
      paddingBottom: 1,
    }}
  >
    dev@aoramind.com
  </a>
);

const SECTIONS: Section[] = [
  {
    index: "01",
    title: "What we collect",
    body: (
      <>
        Account information you provide (email, shipping address, payment
        details processed by our payment provider), biometric signal data
        generated by AORA Nano (ECG, PPG, and early neural potentials), device
        telemetry (firmware version, battery state, diagnostic events), and
        Chrome extension usage if you install it.
      </>
    ),
  },
  {
    index: "02",
    title: "On-device first",
    body: (
      <>
        Raw signals are processed locally on Nano. Only the derivatives you
        explicitly choose to sync leave the device. You can operate Nano in a
        fully offline mode at any time.
      </>
    ),
  },
  {
    index: "03",
    title: "What we never do",
    body: (
      <>
        We do not sell your data. We do not share it with advertisers. We do
        not share it with insurers or employers. We do not train third-party
        models on your biometric data.
      </>
    ),
  },
  {
    index: "04",
    title: "Service providers",
    body: (
      <>
        We rely on a small set of named processors to run the service: a
        payment processor for pre-orders, a cloud host for the account layer,
        a transactional email provider, and privacy-respecting product
        analytics. Each is contractually bound to the same privacy standards
        described here.
      </>
    ),
  },
  {
    index: "05",
    title: "Your rights",
    body: (
      <>
        You may request export, deletion, or portability of your data at any
        time. Email {EMAIL_LINK} and we will action the request within thirty
        days. Deletion is permanent and removes derivatives from our systems
        and from active backups on their normal rotation.
      </>
    ),
  },
  {
    index: "06",
    title: "Cookies and tracking",
    body: (
      <>
        We use strictly necessary cookies to keep you logged in and
        anonymous, aggregated product analytics to understand which parts of
        the service are used. We do not use third-party advertising
        trackers.
      </>
    ),
  },
  {
    index: "07",
    title: "Children",
    body: (
      <>
        The service is not intended for users under eighteen. We do not
        knowingly collect data from children. If you believe a minor has
        created an account, email {EMAIL_LINK} and we will remove it.
      </>
    ),
  },
  {
    index: "08",
    title: "International transfers",
    body: (
      <>
        Data may be processed in the United States. Where required by law,
        transfers are governed by standard contractual clauses or equivalent
        mechanisms.
      </>
    ),
  },
  {
    index: "09",
    title: "Security",
    body: (
      <>
        Data is encrypted in transit and at rest. On-device keys are stored
        in a protected element. No system is perfectly secure; if we ever
        detect a breach that affects you, we will notify you without undue
        delay.
      </>
    ),
  },
  {
    index: "10",
    title: "Changes",
    body: (
      <>
        We will post updates to this policy here with a new effective date.
        Material changes are announced to account holders in advance.
      </>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main className="min-h-[100dvh]">
        {/* ═══════════════════ Hero masthead ═══════════════════ */}
        <section
          className="relative px-6 md:px-10 pt-36 md:pt-48 pb-24 md:pb-32 min-h-[70svh] flex flex-col justify-end overflow-hidden"
          style={{ backgroundColor: "var(--ink)" }}
          aria-labelledby="privacy-heading"
        >
          <div
            aria-hidden
            className="absolute inset-0 pointer-events-none"
            style={{
              background:
                "radial-gradient(ellipse at 20% 0%, rgba(110,139,61,0.08) 0%, rgba(10,10,10,0) 55%), linear-gradient(to bottom, rgba(20,20,20,0.6) 0%, rgba(10,10,10,0) 30%)",
            }}
          />

          <div className="relative mx-auto w-full" style={{ maxWidth: "72rem" }}>
            <a
              href="/"
              className="small-caps inline-flex items-center gap-2 transition-colors duration-150"
              style={{ color: "var(--mute)" }}
            >
              <span aria-hidden>←</span>
              <span>Aora</span>
            </a>

            <div className="mt-10 md:mt-14">
              <SmallCaps>Privacy · Effective April 2026</SmallCaps>
            </div>

            <h1
              id="privacy-heading"
              className="mt-6 font-display font-light leading-[0.98] tracking-tightest text-[40px] sm:text-[56px] md:text-[80px] lg:text-[104px]"
              style={{ color: "var(--paper)" }}
            >
              On-device
              <br />
              first.
            </h1>

            <p
              className="mt-10 md:mt-14 font-display font-light text-xl md:text-2xl leading-[1.45]"
              style={{ color: "var(--paper)", maxWidth: "44rem" }}
            >
              This policy describes what Aora, Inc. collects, how we process
              it, what we never do with it, and the rights you have over the
              data you generate with AORA Nano.
            </p>

            <div className="mt-12 flex flex-wrap items-center gap-x-6 gap-y-3">
              <SmallCaps>Aora, Inc.</SmallCaps>
              <span aria-hidden style={{ color: "var(--mute)" }}>
                ·
              </span>
              <SmallCaps>Effective Apr 2026</SmallCaps>
              <span aria-hidden style={{ color: "var(--mute)" }}>
                ·
              </span>
              <SmallCaps>Data never sold</SmallCaps>
            </div>
          </div>

          <div
            aria-hidden
            className="relative mt-20 md:mt-28 mx-auto w-full"
            style={{
              maxWidth: "72rem",
              height: 1,
              backgroundColor: "var(--rule)",
            }}
          />
        </section>

        {/* ═══════════════════ Policy body ═══════════════════ */}
        <section
          className="px-6 md:px-10 py-20 md:py-28"
          style={{ backgroundColor: "var(--ink-raised)" }}
          aria-labelledby="privacy-body-heading"
        >
          <div className="mx-auto" style={{ maxWidth: "64rem" }}>
            <FadeUp>
              <div id="privacy-body-heading">
                <SmallCaps>Sections</SmallCaps>
              </div>
            </FadeUp>

            <FadeUp delay={0.08}>
              <ol
                className="mt-8 flex flex-col"
                style={{ borderTop: "1px solid var(--rule)" }}
              >
                {SECTIONS.map((s) => (
                  <li
                    key={s.index}
                    className="py-8 md:py-10 flex flex-col md:flex-row md:items-baseline gap-4 md:gap-8"
                    style={{ borderBottom: "1px solid var(--rule)" }}
                  >
                    <span
                      className="font-mono text-sm tracking-wider shrink-0 md:pt-2"
                      style={{ color: "var(--green)" }}
                    >
                      {s.index}
                    </span>
                    <div className="flex-1 min-w-0">
                      <h2
                        className="font-display font-light leading-[1.15] tracking-tightest text-[24px] sm:text-[28px] md:text-[32px]"
                        style={{ color: "var(--paper)" }}
                      >
                        {s.title}
                      </h2>
                      <p
                        className="mt-4 font-display font-light text-base md:text-[17px] leading-[1.55]"
                        style={{ color: "var(--mute)", maxWidth: "44rem" }}
                      >
                        {s.body}
                      </p>
                    </div>
                  </li>
                ))}
              </ol>
            </FadeUp>
          </div>
        </section>

        {/* ═══════════════════ Contact / Footer CTA ═══════════════════ */}
        <section
          className="px-6 md:px-10 py-24 md:py-32"
          style={{ backgroundColor: "var(--ink)" }}
          aria-labelledby="privacy-contact-heading"
        >
          <div
            className="mx-auto grid grid-cols-1 md:grid-cols-[1.4fr_1fr] gap-12 md:gap-20"
            style={{ maxWidth: "64rem" }}
          >
            <div>
              <FadeUp>
                <SmallCaps>Contact</SmallCaps>
              </FadeUp>
              <FadeUp delay={0.08}>
                <h3
                  id="privacy-contact-heading"
                  className="mt-6 font-display font-light leading-[1.08] tracking-tightest text-[30px] sm:text-[36px] md:text-[40px]"
                  style={{ color: "var(--paper)" }}
                >
                  Questions about your data? Write to us.
                </h3>
              </FadeUp>
              <FadeUp delay={0.15}>
                <div className="mt-10">
                  <a
                    href="mailto:dev@aoramind.com"
                    className="inline-flex items-center gap-2 font-display text-lg transition-colors duration-150"
                    style={{ color: "var(--paper)" }}
                  >
                    <span
                      style={{
                        borderBottom: "1px solid var(--green)",
                        paddingBottom: 2,
                      }}
                    >
                      dev@aoramind.com
                    </span>
                    <span aria-hidden>→</span>
                  </a>
                </div>
              </FadeUp>
            </div>

            <div
              className="md:border-l md:pl-12"
              style={{ borderColor: "var(--rule)" }}
            >
              <FadeUp delay={0.1}>
                <SmallCaps>More from Aora</SmallCaps>
              </FadeUp>
              <FadeUp delay={0.18}>
                <ul className="mt-6 flex flex-col gap-4">
                  {[
                    { label: "Home", href: "/" },
                    { label: "Product", href: "/product" },
                    { label: "FAQ", href: "/faq" },
                    { label: "Terms", href: "/terms" },
                  ].map((l) => (
                    <li key={l.label}>
                      <a
                        href={l.href}
                        className="small-caps inline-flex items-center gap-2 transition-colors duration-150"
                        style={{ color: "var(--paper)" }}
                      >
                        <span>{l.label}</span>
                        <span aria-hidden style={{ color: "var(--green)" }}>
                          →
                        </span>
                      </a>
                    </li>
                  ))}
                </ul>
              </FadeUp>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
